version: "3.9"

services:
  chatroom-postgres:
    image: postgres:14
    container_name: chatroom-postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: chatroom
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql

volumes:
  postgres-data:
