version: "3.9"

services:
  chatroom-postgres:
    image: postgres:15
    container_name: chatroom-postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: chatroom
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql

  chatroom-redis:
    container_name: chatroom-redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  chatroom-localstack:
    container_name: chatroom-localstack
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT: http://127.0.0.1:4566
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      DATA_DIR: /tmp/localstack/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack-setup.sh:/etc/localstack/init/ready.d/localstack-setup.sh
      - ./resources:/usr/share/app/resources

volumes:
  postgres-data:
