name: Build & Test

on: push

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Docker Compose
        run: docker-compose up -d

      - name: Configure CMake
        run: |
          docker run -t wsekta/chatroom-builder -v ${{github.workspace}}:/home/chatroom -w /home/chatroom \
            --entrypoint \
              cmake -B ${{github.workspace}}/build \
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16 \
                -DCODE_COVERAGE:BOOL=ON \
                -GNinja

      - name: Build
        run: |
          docker run -t wsekta/chatroom-builder -v ${{github.workspace}}:/home/chatroom -w /home/chatroom \
            --entrypoint \
              cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Prepare environment files
        run: |
          mv apps/client/.env.example apps/client/.env \
          && mv apps/server/.env.example apps/server/.env

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          docker run -t wsekta/chatroom-builder -v ${{github.workspace}}:/home/chatroom -w /home/chatroom \
            --entrypoint \
              ninja chatroom-ccov-all \
              && llvm-cov-16 show `cat ccov/binaries.list` -instr-profile=ccov/all-merged.profdata > coverage.txt

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOVTOKEN }}

      - name: Stop containers
        if: always()
        run: docker-compose down
