name: Build & Test

on: push

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install apt-get dependencies
        run: |
          sudo apt-get update \
           && sudo apt-get install -y  ninja-build  build-essential libstdc++-13-dev lcov \
             libboost-dev libgl1-mesa-dev libglx-dev \
             qt6-base-dev libqt6sql6-psql libqt6qml6 qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools qt6-svg-dev \
             qml6-module-qtquick-controls qml6-module-qtqml-workerscript qml6-module-qtquick-templates qml6-module-qt5compat-graphicaleffects \
             postgresql libcutl-1.10 libpq-dev sqlite3 libsqlite3-dev odb\
           && sudo systemctl stop postgresql

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"

      - name: Docker Compose
        run: docker-compose up -d

      - name: Install external CMake package
        run: cd externals && ./install_externals.sh
        env:
          BUILD_TYPE: ${{env.BUILD_TYPE}}

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16 \
            -DCODE_COVERAGE:BOOL=ON \
            -GNinja

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Prepare environment files
        run: |
          mv apps/client/.env.example apps/client/.env \
          && mv apps/server/.env.example apps/server/.env

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ninja chatroom-ccov-all \
          && llvm-cov-16 show `cat ccov/binaries.list` -instr-profile=ccov/all-merged.profdata > coverage.txt

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOVTOKEN }}

      - name: Stop containers
        if: always()
        run: docker-compose down
