name: CMake

on: push

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install apt-get dependencies
        run: |
          sudo add-apt-repository ppa:mhier/libboost-latest -y \
            && sudo add-apt-repository ppa:trebelnik-stefina/launchpad-getkeys \
            && sudo apt-get update \
            && sudo apt-get install launchpad-getkeys \
            && sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main' \
            && sudo launchpad-getkeys \
            && sudo apt-get update -y \
            && sudo apt-get install -y lld-16 ninja-build  build-essential libstdc++-13-dev \
              clang-16 clang-tools-16 llvm-16  \
              libboost1.82-dev libgl1-mesa-dev libglx-dev librange-v3-dev \
              qt6-base-dev libqt6sql6-psql libqt6qml6 qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools \
              qml6-module-qtquick-controls qml6-module-qtqml-workerscript qml6-module-qtquick-templates

      - name: Install external CMake package
        run: cd externals && ./install_externals.sh
        env:
          BUILD_TYPE: ${{env.BUILD_TYPE}}

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16 \
            -DINTEGRATION_TESTS_BUILD=OFF \
            -DENABLE_COVERAGE=ON \
            -GNinja

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -V

      - name: Codecov
        run: |
          curl -S -f https://codecov.io/bash -o codecov 
            && chmod +x codecov
            &&  ./codecov -x "llvm-cov-16 gcov" -Z -t ${{ secrets.CODECOVTOKEN }}

#        uses: codecov/codecov-action@v3.1.4
#        with:
#          token: ${{ secrets.CODECOVTOKEN }}
#          gcov: true
#          gcov_executable: llvm-cov-16 gcov
