name: CMake

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache apt
        id: cache-apt
        uses: actions/cache@v3
        with:
          path: |
            README.md
            .github/workflows/cmake.yml
          key: ${{ runner.os }}-apt

      - name: Install apt-get dependencies
        if: steps.cache-apt.outputs.cache-hit != 'true'
        run: |
          sudo add-apt-repository ppa:mhier/libboost-latest -y \
            && sudo add-apt-repository ppa:trebelnik-stefina/launchpad-getkeys \
            && sudo apt-get update \
            && sudo apt-get install launchpad-getkeys \
            && sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main' \
            && sudo launchpad-getkeys \
            && sudo apt-get update -y \
            && sudo apt-get install -y lld-16 ninja-build  build-essential libstdc++-13-dev \
              clang-16 clang-tools-16  \
              libboost1.82-dev libgl1-mesa-dev libglx-dev librange-v3-dev \
              qt6-base-dev libqt6sql6-psql libqt6qml6 qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools \
              qml6-module-qtquick-controls qml6-module-qtqml-workerscript qml6-module-qtquick-templates

      - name: Cache externals
        id: cache-external
        uses: actions/cache@v3
        with:
          path: externals/
          key: ${{ runner.os }}-external

      - name: Install external CMake package
        if: steps.cache-external.outputs.cache-hit != 'true'
        run: cd externals && ./install_externals.sh
        env:
          BUILD_TYPE: ${{env.BUILD_TYPE}}

      - name: Install apt-get dependencies
        if: steps.cache-apt.outputs.cache-hit != 'true'
        run: |
          ls && ls chatroom
#      - name: Configure CMake
#        run: |
#          cmake -B ${{github.workspace}}/build \
#            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
#            -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16 \
#            -DINTEGRATION_TESTS_BUILD=OFF \
#            -GNinja
#
#      - name: Build
#        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
#
#      - name: Test
#        working-directory: ${{github.workspace}}/build
#        run: ctest -C ${{env.BUILD_TYPE}} -V
